### ISSUE TITLE
[BACKEND] getTasks throws error

### ISSUE THREAD

**Issue by emtseng** [sb2483/MealPool#9]
Got an error when I tried to run a get to /api/tasks:

```
ERROR [2017-11-15 17:21:23,905] io.dropwizard.jersey.errors.LoggingExceptionMapper: Error handling a request: 2522e2d9e02ade16
! java.util.UnknownFormatConversionException: Conversion = 'to'
! at java.util.Formatter$FormatSpecifier.checkDateTime(Formatter.java:2963)
! at java.util.Formatter$FormatSpecifier.<init>(Formatter.java:2723)
! at java.util.Formatter.parse(Formatter.java:2560)
! at java.util.Formatter.format(Formatter.java:2501)
! at java.util.Formatter.format(Formatter.java:2455)
! at java.lang.String.format(String.java:2940)
! at api.TaskResource.create(TaskResource.java:33)
! at controllers.TaskController.getTodaysReminder(TaskController.java:97)
! at controllers.TaskController.getTasks(TaskController.java:48)
```

**Comment by sb2483** [comment]
Please give me some more information. Who were you loved in as? Did you take any specific actions between logging in and displaying tasks that would alter which tasks you expect to see?

**Comment by emtseng** [comment]
Logged in as Ryan, rzl6@cornell.edu, password "pw". No actions. Worth noting also this was working last night.

**Comment by sb2483** [comment]
Yeah and I haven't changed anything. I'll have to look at it during startup
systems.

**Comment by sb2483** [comment]
Issue resolved in develop

**Comment by emtseng** [comment]
I'm curious, what was the problem?

**Comment by sb2483** [comment]
It was a stupid oversight. When calling String.format(), it expects to see %s for all places in the string to be replaced, and in one of the task messages I forgot the s, so it just had %.

**Comment by emtseng** [comment]
Gotcha. Thanks!
